name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      # Grant exec perms for ./gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Run spotless code formatting
      - name: Spotless formatting check
        run: ./gradlew spotlessCheck --max-workers 1
      # Run only build tasks without tests, that way we can build the JNIs first that the tests depend on
      - name: Gradle build
        run: ./gradlew build -x check --max-workers 2
      # Run gradle tests.
      - name: Gradle tests
        run: ./gradlew test --max-workers 1 --stacktrace
      # Upload gradle test report.
      - name: Upload gradle test report
        uses: actions/upload-artifact@v3
        with:
          name: gradle-test-report
          path: build/reports/tests/test/
